### ISSUE TITLE
Update to guacamole 1.5.0

### ISSUE THREAD

**Issue by netbix** [jwetzell/docker-guacamole#11]
**Describe Your Problem:**
Predictions for update 1.5.0 ?

**Logs:**

```
Remove any sensative information.
```

**Screenshots:**

**Environment:**

* **Guacamole Version**: 1.4.0
* **Operating System**:  Docker

**Comment by jwetzell** [comment]
Thanks, didn't see the release. I am on it now should be done by EOD.

**Comment by jwetzell** [comment]
@netbix 1.5.0-amd64 image is up and working. I am still getting the tooling back together to build the arm images.

**Comment by netbix** [comment]
Thank you

It works great

**Comment by jwetzell** [comment]
Perfect!
