### ISSUE TITLE
Architecture mismatch with the latest version 1.5.0

### ISSUE THREAD

**Issue by CypZ** [jwetzell/docker-guacamole#13]
**Describe The Bug:**
With the latest version 1.5.0 I had to fix the version in the docker compose file (jwetzell/guacamole:1.5.0-arm64), because there is a mismatch of the architecture in the Docker Image file (jwetzell/guacamole:arm64)

**To Reproduce:**
Dockerfile jwetzell/guacamole:arm64 line 27:amd64 (instead of arm64)
Dockerfile jwetzell/guacamole:1.5.0-arm64 line 27 armhf is correct.

**Expected behavior:**
Dockerfile jwetzell/guacamole:arm64 line 27:armhf or arm64

**Environment:**
* **Guacamole Version**: 1.5.0 (docker arm64)
* **Operating System**: Linux ssch1 5.10.0-20-arm64 #1 SMP Debian 5.10.158-2 (2022-12-13) aarch64 GNU/Linux

**Comment by jwetzell** [comment]
I think I have corrected this now. @CypZ

**Comment by CypZ** [comment]
confirmed working, thanks

**Comment by CypZ** [comment]
Again, same error tag=arm64 and tag=1.5.1-arm64

Bring my prod dowwn each and every time...

**Comment by jwetzell** [comment]
Ok, I will take a look, rebuild, and reupload

**Comment by CypZ** [comment]
hint: typo in the build pipeline ? Confusion between amd64 and arm64 ?

**Comment by jwetzell** [comment]
I think what happen was I built it using the arm image but didn't change the ARCH environment variable so it still installed the amd64 version of guacamole/s6-overlay, etc.

**Comment by jwetzell** [comment]
alright @CypZ lets try this again. New images should be pushed as well as 1.5.2 which recently came out.

**Comment by CypZ** [comment]
yes, (I only tested) the latest image with the tag arm64 (1.5.2 as of today) has now the correct arch.

Finger crossed for the next version ;)

**Comment by jwetzell** [comment]
I've hopefully laid things out so I can't screw this up next time.
