### ISSUE TITLE
RDP connection to Windows Server 2019 disconnects immediately at login. Error log message *** Error in `guacd': double free or corruption (fasttop): 0x016880d8 ***

### ISSUE THREAD

**Issue by christyler80** [jwetzell/docker-guacamole#14]

**Comment by christyler80** [comment]
Raspberry Pi 4 8GB 64bit Raspberry OS. Error log as follows.....

guacd[280]: INFO:	Creating new client for protocol "rdp"
guacd[280]: INFO:	Connection ID is "$0321406a-7eb9-491e-92e0-db5cf78aae3e"
guacd[445]: INFO:	Security mode: NLA
guacd[445]: INFO:	Resize method: display-update
guacd[445]: INFO:	No clipboard line-ending normalization specified. Defaulting to preserving the format of all line endings.
guacd[445]: INFO:	User "@2f85ab57-a324-4e9a-ad65-0d1fe462bece" joined connection "$0321406a-7eb9-491e-92e0-db5cf78aae3e" (1 users now present)
20:37:48.990 [http-nio-8080-exec-9] INFO  o.a.g.tunnel.TunnelRequestService - User "sysadmin" connected to connection "1".
guacd[445]: INFO:	Loading keymap "base"
guacd[445]: INFO:	Loading keymap "en-us-qwerty"
guacd[445]: INFO:	Connected to RDPDR 1.13 as client 0x0002
*** Error in `guacd': double free or corruption (fasttop): 0x016880d8 ***
guacd[280]: INFO:	Connection "$0321406a-7eb9-491e-92e0-db5cf78aae3e" removed.
20:37:53.785 [Thread-9] INFO  o.a.g.tunnel.TunnelRequestService - User "sysadmin" disconnected from connection "1". Duration: 4795 milliseconds

**Comment by jwetzell** [comment]
I think I'm going to need a little more than "Hi," to know what your issue is?

**Comment by christyler80** [comment]
Hi Joel,

 

Sorry, about the ‘Hi’ – pressed the wrong key whilst typing…

 

I have now posted the details into GitHub including error log messages.

 

Please let me know if you need more information.

 

Many Thanks

 

Chris

**Comment by jwetzell** [comment]
When I get a chance I will try booting up the image on a raspberry pi. Do you have what version of the image you are using?

**Comment by jwetzell** [comment]
I don't know. There is an arm64 image: `jwetzell/guacamole:1.5.0-arm64`

**Comment by christyler80** [comment]
Joel,

 

Good news, it has worked!!

 

Thank you and for the work you have put into your project.

 

FYI, I have had to change a couple of registry settings on my server - Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp "UserAuthentication" is 0 and "SecurityLayer" is 1

 

This info is from discussion on the Internet and I believe these settings are needed for Windows 10 as well.

 

Best Regards

 

Chris
