### ISSUE TITLE
Please include https://github.com/apache/guacamole-server/pull/418 

### ISSUE THREAD

**Issue by SurinameClubcard** [jwetzell/docker-guacamole#18]
I'm suffering from a bug mentioned in above URL (GUACAMOLE-1717). A fix was recently merged in apache:master. Could you include it as well so that https://hub.docker.com/r/jwetzell/guacamole works correctly? Tnx!

**Comment by jwetzell** [comment]
When they release 1.5.2 which it looks like 1717 is included in I can update this image to that.

**Comment by retronexus** [comment]
Excellent, I have issues with the mouse pointer through RDP into Ubuntu. That seems to be a bug with guacd

**Comment by jwetzell** [comment]
They have released 1.5.2 and I have built and published the 1.5.2-amd64 image which at least in my test setup fixes this issue with the cursors.

**Comment by retronexus** [comment]
Just perfect, thanks for your work and contribution!!
