### ISSUE TITLE
Cannot enable sound

### ISSUE THREAD

**Issue by ghost** [jwetzell/docker-guacamole#19]
Truth be told, I've never had sound but gave up whenever I saw the onzu build had been discontinued. I found this, updated just the image to be: 

  guacamole:  # External web vnc
    container_name: guacamole
    image: jwetzell/guacamole:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./guacamole/data:/config
    environment:
      - EXTENSIONS=auth-totp
    networks:
      - gate

I have a sound adapter and a volume slider, just no sound emits from the browser. Everything else works. 

Here are logs, NOTE: The rejection was because I didn't actually log out then back in after changing the image, once I did that it was fine. 

[guaclogs.txt](https://github.com/jwetzell/docker-guacamole/files/11537510/guaclogs.txt)

**Comment by jwetzell** [comment]
I would always specify the version of the image to use (instead of latest). But i've been using 1.5.1-amd64 and have audio working with a Windows 10 VM and RDP. I'm not sure what you are RDP'ing into but the RDP server need to support audio redirection. I think there are also some connection options regarding audio not sure what they effect though.

**Comment by negativzeroe** [comment]
Yeah it's set up standard rdp and when I use the rdp client I have audio.

**Comment by negativzeroe** [comment]
I double checked and have nothing regarding sound disabled.

**Comment by negativzeroe** [comment]
Also changed to the specific tag and no sound.

**Comment by jwetzell** [comment]
The only thing I can see is that your logs have some sort of WebSocket error with some HttpTunnel fallback and no audio stream picked up. Here is a snippet from my connection to RDP with working audio.

```
guacd[361]: INFO:	Loading keymap "en-us-qwerty" 23:29:15.075 [http-nio-8080-exec-1] 
INFO  o.a.g.tunnel.TunnelRequestService - User "<USERNAME>" connected to connection "32".
guacd[361]: INFO:	Connected to RDPDR 1.13 as client 0x0003
guacd[361]: INFO:	Connected to RDPDR 1.13 as client 0x0002
guacd[361]: INFO:	RDPDR user logged on
guacd[361]: INFO:	Accepted format: 16-bit PCM with 2 channels at 44100 Hz
```

and here is from your logs

```
guacd[593]: INFO:	Loading keymap "en-us-qwerty" 22:21:25.452 [http-nio-8080-exec-6] 
INFO  o.a.g.tunnel.TunnelRequestService - User "negativzeroe" connected to connection "1". 22:21:25.452 [http-nio-8080-exec-6] 
INFO  o.a.g.t.h.RestrictedGuacamoleHTTPTunnelServlet - Using HTTP tunnel (not WebSocket). Performance may be sub-optimal.
guacd[593]: INFO:	Connected to RDPDR 1.13 as client 0x0003
guacd[593]: INFO:	Connected to RDPDR 1.13 as client 0x0002
guacd[593]: INFO:	RDPDR user logged on
```

**Comment by jwetzell** [comment]
In the meanwhile I will continue trying to get it to break, trying may I know what OS you are running so I can try to setup a similar setup.

**Comment by negativzeroe** [comment]
My host is Debian Bullseye - and I'm running the VM on kvm. Here is my xml from it. Note, When using the Windows RDP client (mstsc) I had sound prior to installing this sound card, I added it as a troubleshooting step based on something I read elsewhere which gave me a volume slider in guacamole (as opposed to a red X), so I'm partially there with that, just the sound doesn't emit lol. 
[win10.xml.md](https://github.com/jwetzell/docker-guacamole/files/11544308/win10.xml.md)

**Comment by negativzeroe** [comment]
Just following up on this. Not sure what else to do.

**Comment by negativzeroe** [comment]
Okay - just to clarify it is a windows vm, just running on KVM linux host.
