### ISSUE TITLE
Radius Authentication

### ISSUE THREAD

**Issue by vanderpunk** [jwetzell/docker-guacamole#21]
Having trouble getting instance of Guacamole to connect to an LDAP server. I was able to get one of my instances of Guacamole to connect to a Synology NAS LDAP server. I'm having trouble getting a seperate instance to connect to an LDAP server (Azure AD LDAP Wrapper). A different Synology NAS was able to connect to the LDAP Wrapper server, and hosts a RADIUS server. I was wondering if you could add RADIUS support for authentication?

**Environment:**

* **Guacamole Version**: jwetzell/guacamole:latest
* **Operating System**:  Docker

**Comment by jwetzell** [comment]
Looks like that would require building the guacamole-server from source which is not something I'm setup to do.
