### ISSUE TITLE
Can you please add connection support for IPv6?

### ISSUE THREAD

**Issue by notetoday** [jwetzell/docker-guacamole#22]
Can you please add connection support for IPv6?

**Comment by jwetzell** [comment]
Does Apache Guacamole support IPv6?

**Comment by notetoday** [comment]
> Does Apache Guacamole support IPv6?

😅 I'm not sure, but there is such a need, so I asked this question

**Comment by notetoday** [comment]
> Figuring out whether or not Apache Guacamole works with IPv6 would be required before I would be able to say whether or not this image could support it.

 OK, thank you very much for your reply, thank you

**Comment by alexshalex** [comment]
Apache Guacamole works fine with IPv6, but need add support in Docker ipv6 https://docs.docker.com/config/daemon/ipv6/

**Comment by notetoday** [comment]
> Apache Guacamole works fine with IPv6, but need add support in Docker ipv6 https://docs.docker.com/config/daemon/ipv6/

Thank you for your answer, it solved my problem perfectly. Thanks
