### ISSUE TITLE
Add noauth extension

### ISSUE THREAD

**Issue by Rothmanberger** [jwetzell/docker-guacamole#24]
Would it be possible to add in noauth? I use my own authentication over the top so currently I have to log in to two different forms to get to Guac.

Thanks!

**Comment by jwetzell** [comment]
If you can find a noauth extension from Apache for version 1.5.3 I can try adding it under a different tag. But the default image already has the auth extension and that will likely stay as this is an image that is supposed to be backwards compatible with the fork it came from.
