### ISSUE TITLE
Bump to version 1.5.4

### ISSUE THREAD

**Issue by mariushosting** [jwetzell/docker-guacamole#25]
@jwetzell Please bump guacamole to the new version 1.5.4

**Comment by jwetzell** [comment]
Waiting for a bug in building 1.5.4 to be sorted out I'm currently experiencing what [this user](https://www.mail-archive.com/user@guacamole.apache.org/msg12454.html) is.

**Comment by jwetzell** [comment]
@mariushosting images for 1.5.4 (amd64 and arm64) are up now.

**Comment by mariushosting** [comment]
> @mariushosting images for 1.5.4 (amd64 and arm64) are up now.

Awesome!!!
