### ISSUE TITLE
Guacamole Server unavailable

### ISSUE THREAD

**Issue by IkaSGC** [jwetzell/docker-guacamole#32]
Hi, I have no idea what it's doing. 
I installed it in portrainer using a script: 

`version: "2"
services:
  guacamole:
    image: jwetzell/guacamole
    container_name: guacamole-new
    volumes:
      - /volume1/docker/guacamole:/config
    ports:
      - 8082:8080
    environment:
      EXTENSIONS: auth-ldap,auth-totp
volumes:
  postgres:
    driver: local`

I created both RDP and VNC. Neither connection works. The session always connects and disconnects immediately, saying that the "guacamole server" is unavailable. 
I deleted the whole thing and reinstalled it, all of a sudden there was a two-factor authentication that wasn't there before. Anyway, same error. 

![419723934_376158701673300_661097487570819509_n](https://github.com/jwetzell/docker-guacamole/assets/7561343/07d46438-53cb-4a6d-82da-80a0721d264c)

Then when I clicked Reconnect, it logged me out every time. It was like it had a life of its own. 
Is there any way to install an older version ??

**Comment by IkaSGC** [comment]
Third try to reinstall it...... 

Connecting via RDP. It starts logging me in, then kicks me out and pops up this error. 

![image](https://github.com/jwetzell/docker-guacamole/assets/7561343/1f9465ae-4276-4bbe-bc3c-2391ceefdc75)

**Comment by jwetzell** [comment]
Ok, what version of the image are you using? I don't know what script you are using to install so I'm not sure I'm going to be of much help there. The extension listed in this snippet  `environment: EXTENSIONS: auth-ldap,auth-totp` say to turn on LDAP for auth and TOTP (two-factor auth).

**Comment by IkaSGC** [comment]
Sorry for the chaos....

I make clean instaal with this script: 
![image](https://github.com/jwetzell/docker-guacamole/assets/7561343/79058e3d-3cc8-46a7-abd2-f6fbb15f56f4)

When i test VNC Connect, the computer logs in and then kicks me off with this message:

![ScreenHunter_07 Jan  17 20 39](https://github.com/jwetzell/docker-guacamole/assets/7561343/b44a4543-e2f3-446a-8f92-a27f1a0f405c)

I've now tried connecting to Windows 10 via RDP. No luck on the first 5 or so attempts. I then connected to that computer via RDP from windows. Once I was connected, I put the connection through guacamole again and suddenly it connected me. 

![image](https://github.com/jwetzell/docker-guacamole/assets/7561343/5a68632a-0ec7-488a-ad30-bee8780823dd)

But as soon as I do something on the computer, it kicks me off immediately. Everything runs on a pretty decent synology NAS. If I try to connect to Server 2019 I get "disconnected" or "Guacamole not available"

**Comment by jwetzell** [comment]
I would start by specifying a version for the image as I said without that I have no idea what version you are running.

I don't know what effects all the extra settings in that docker-compose file especially the PUID and PGID environment variables not sure there is any support for non-root user execution (I at least have never tested it).

**Comment by IkaSGC** [comment]
Where i can find what version it is?? I checked everywhere in GUI, but i cant find version number.

**Comment by jwetzell** [comment]
The Guacamole web interface doesn't have a way to view the version as far as I know. You would specify the version when you are telling it what image to use `jwetzell/guacamole:<put tag name here>` for this container. See me comment earlier for the link to view what tags are available.

**Comment by IkaSGC** [comment]
Ok, I apologize again. 
There is no version defined in the script, so I assume it is some default? I don't know. To avoid confusion, I uninstalled and installed everything with the "latest" parameter.
In guacamole, I created an RDP connection to Windows 2019.

![Screen_02 Jan  18 06 17](https://github.com/jwetzell/docker-guacamole/assets/7561343/eee20a54-67db-4171-8ddb-52f9e7e38fb4)
![image](https://github.com/jwetzell/docker-guacamole/assets/7561343/970b7316-bff4-44fe-9a9a-f690459521bf)

Name, Domain, Passwd are 100% correct. 
RDP works quite normally when connecting from windows.

It says only "You have ben disconnected"

![image](https://github.com/jwetzell/docker-guacamole/assets/7561343/92c5113a-9f17-4281-9cd4-ec261e848a29)

**Comment by jwetzell** [comment]
You should not use latest if you care about what exact version you are running as that tag can update at ANY time and your system may or may not be setup to pull that newer version in. Have you removed the extra environment variables particularly PUID and PGID to see if that is causing the issue. If that doesn't resolve it I'm not sure I have any other ideas. The image definitely works as it stands (and when configured as documented) I have multiple instances running personally and know of others that are running with no issue.

**Comment by IkaSGC** [comment]
Problem solved. The problem was not with Guacamole, but with DNS/SMB.

https://bugzilla.samba.org/show_bug.cgi?id=15418

**Comment by jwetzell** [comment]
Perfect!
