### ISSUE TITLE
Change default username and password during start-up.

### ISSUE THREAD

**Issue by Samarthasnani97** [jwetzell/docker-guacamole#33]
I downloaded the latest version of dockerfile, and trying build the dockerfile rather than building the image and when my dockerfile is built and running, and try to access the apache guacamole with default ID and password "guacadmin" , it gives an incorrect password. Althought the init.sql file is already present inside the guacamole folder. I am very new to apache guacamole

**Comment by jwetzell** [comment]
Can you give some context to how you are building the image and how you are running it (potentially example commands you are running)? I just built and ran the `master` branch and could successfully log in with the username and password `guacadmin`.

**Comment by Samarthasnani97** [comment]
Actually rather than pulling the image I am trying to use the raw docker file for which you have provided the source code, I am simply making a new dockerfile and also copying the whole root folder in the same directory as the dockerfile and building the dockerfile, after running the file the default user name and password it is showing me as incorrect.

**Comment by jwetzell** [comment]
Sorry I don't see how can help further unless you provide steps to reproduce this problem. Like I said I tested building and running the main branch after you opened the issue and found no problem with the image. To test this I cloned this repository and inside ran `docker build` against the `Dockerfile.amd64` file and then ran the image that was built and could login just fine.

**Comment by Samarthasnani97** [comment]
I am sorry for not describing my question clearly.. I am able to build the docker image..I want to actually change the default username and password that is "guacadmin" during the start-up. I know that I can change it after logging in but I want to change it during the startup so that the user can directly put the user defined user name and password in place of default username and password. Please provide me some solution.

Thankyou in advance.

**Comment by jwetzell** [comment]
You would need to modify the contents of `/app/guacamole/schema/002-create-admin-user.sql`. That schema folder is part of the [postgresql extension](https://github.com/apache/guacamole-client/blob/22fe53fde50fd139cb86091912e1ae50d348add8/extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/schema/002-create-admin-user.sql) ([relevant part of the Dockerfile](https://github.com/jwetzell/docker-guacamole/blob/a4f9da42e2762a066afafa8463986bd8edcfa7d8/Dockerfile#L32C1-L32C82)) which sets up the database on first boot and setting up the default admin account is part of that.

**Comment by Samarthasnani97** [comment]
Perfect, Thankyou so much, Can you also help me on to how to generate the salt and hash password which similar to which apache guacamole is using, is there any tool to generate the password.

**Comment by jwetzell** [comment]
I don't know what hashing algorithm they are using or how they are combining the hash. Should be able to find that with some googling. A quick and dirty approach would be to just set a password via the UI and then pull the password_hash and password_salt columns out of that table.

**Comment by Samarthasnani97** [comment]
Perfect it working now, I was able to change the default user name and password, Thankyou so much for the solution. 
Now, If I want to do some changes on the client UI like removing some extra columns in settings, where should I look for ? Can you please suggest me.

**Comment by jwetzell** [comment]
I don't know, you can go look through the Apache's code [here](https://github.com/apache/guacamole-client) to figure out how to modify and build it. I'll be closing this issue.
