### ISSUE TITLE
is there a public arm64 (macos m1) image?

### ISSUE THREAD

**Issue by sdetweil** [jwetzell/docker-guacamole#34]
the link I used for amd64 
jwetzell/guacamole  got me a AMD64 warning

**Comment by jwetzell** [comment]
Check hub.docker.com for what tags are available there should be an arm64 build. If you use a amd64 image then yes it will be amd64 not sure what else would be expected.

**Comment by sdetweil** [comment]
thanks.. never had to force a tag before..
