### ISSUE TITLE
Synology issue on update

### ISSUE THREAD

**Issue by mdelambilly** [jwetzell/docker-guacamole#36]
Hi,

Just to let you know that I had to delete my local config directory when I updated your image to 1.5.1.
I faced this error : **pg_isready no found**

Thanks for this image ! :)

**Comment by jwetzell** [comment]
Ok, that doesn't give me a whole lot to go on. 1.5.1 was pushed about 8 months ago, the latest version is 1.5.4. I've updated my instances as I make and push the new images and have not faced any issue with the upgrades. If you could try updating to the latest image and seeing if there is an issue with that if there is open another issue explaining how I can reproduce the issue so I can further troubleshoot.

**Comment by mdelambilly** [comment]
I updated my image today to your latest which is tagged 1.5.1 !

**Comment by jwetzell** [comment]
Sorry, I'm not seeing where 1.5.1 is the latest [docker hub](https://hub.docker.com/r/jwetzell/guacamole) Can you point me to where you are seeing that?

**Comment by mdelambilly** [comment]
Indeed I mixed github tags and dockerhub tags. I updated to the latest of this one https://hub.docker.com/r/jwetzell/guacamole
to upgrade I just click on the link in container manager app of my SYNO

**Comment by mdelambilly** [comment]
Is that possible it was a totp plugins issue. I has some difficulties to make it work back with the latest image

**Comment by jwetzell** [comment]
I don't have any experience with any container managers or really any of the guacamole plugins. I usually test that they load when specified via environment variables as documented. I can try running the 1.5.4 version which is the latest guacamole version available with the TOTP extension enabled to see if I run into any problems.

**Comment by jwetzell** [comment]
@mdelambilly I just tested 1.5.4-amd64 with auth-totp extension enabled with the Google Authenticator app and that worked just fine.

**Comment by Aryetis** [comment]
I also just recently updated guacamole (last time was probably one or two years ago) and am now facing the same issue. Here's a more complete log.
```
etc etc
2025/02/23 11:17:26 | stdout | Waiting for postgres to come up...
2025/02/23 11:17:26 | stdout | ./run: 3: pg_isready: not found
2025/02/23 11:17:26 | stdout | s6-applyuidgid: fatal: unable to exec postgres: No such file or directory
2025/02/23 11:17:26 | stdout | Starting postgres...
2025/02/23 11:17:25 | stdout | Waiting for postgres to come up...
2025/02/23 11:17:25 | stdout | ./run: 3: pg_isready: not found
2025/02/23 11:17:25 | stdout | s6-applyuidgid: fatal: unable to exec postgres: No such file or directory
2025/02/23 11:17:25 | stdout | Starting postgres...
2025/02/23 11:17:24 | stdout | Waiting for postgres to come up...
2025/02/23 11:17:24 | stdout | ./run: 3: pg_isready: not found
2025/02/23 11:17:24 | stdout | s6-applyuidgid: fatal: unable to exec postgres: No such file or directory
2025/02/23 11:17:24 | stdout | Starting postgres...
2025/02/23 11:17:23 | stdout | Waiting for postgres to come up...
2025/02/23 11:17:23 | stdout | ./run: 3: pg_isready: not found
2025/02/23 11:17:23 | stdout | s6-applyuidgid: fatal: unable to exec postgres: No such file or directory
2025/02/23 11:17:23 | stdout | Starting postgres...
2025/02/23 11:17:22 | stdout | Waiting for postgres to come up...
2025/02/23 11:17:22 | stdout | ./run: 3: pg_isready: not found
2025/02/23 11:17:22 | stdout | s6-applyuidgid: fatal: unable to exec postgres: No such file or directory
2025/02/23 11:17:22 | stdout | Starting postgres...
2025/02/23 11:17:21 | stdout | Waiting for postgres to come up...
2025/02/23 11:17:21 | stdout | ./run: 3: pg_isready: not found
2025/02/23 11:17:21 | stdout | s6-applyuidgid: fatal: unable to exec postgres: No such file or directory
2025/02/23 11:17:21 | stdout | Starting postgres...
2025/02/23 11:17:20 | stdout | guacd[276]: INFO:	Listening on host 127.0.0.1, port 4822
2025/02/23 11:17:20 | stdout | guacd[276]: INFO:	Guacamole proxy daemon (guacd) version 1.5.5 started
2025/02/23 11:17:20 | stdout | [services.d] done.
2025/02/23 11:17:20 | stdout | s6-applyuidgid: fatal: unable to exec postgres: No such file or directory
2025/02/23 11:17:20 | stdout | Waiting for postgres to come up...
2025/02/23 11:17:20 | stdout | ./run: 3: pg_isready: not found
2025/02/23 11:17:20 | stdout | Starting guacamole guacd...
2025/02/23 11:17:20 | stdout | Starting postgres...
2025/02/23 11:17:20 | stdout | [services.d] starting services
2025/02/23 11:17:20 | stdout | [cont-init.d] done.
2025/02/23 11:17:20 | stdout | [cont-init.d] 50-extensions.sh: exited 0.
2025/02/23 11:17:20 | stdout | Cleaning Extensions
2025/02/23 11:17:20 | stdout | Cleaning Extensions from previous Guacamole versions
2025/02/23 11:17:20 | stdout | [cont-init.d] 50-extensions.sh: executing...
2025/02/23 11:17:20 | stdout | [cont-init.d] 40-postgres.sh: exited 0.
2025/02/23 11:17:20 | stdout | Database already configured
2025/02/23 11:17:20 | stdout | [cont-init.d] 40-postgres.sh: executing...
2025/02/23 11:17:20 | stdout | [cont-init.d] 30-defaults.sh: exited 0.
2025/02/23 11:17:19 | stdout | cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
2025/02/23 11:17:19 | stdout | [cont-init.d] 30-defaults.sh: executing...
2025/02/23 11:17:19 | stdout | [cont-init.d] executing container initialization scripts...
2025/02/23 11:17:19 | stdout | [fix-attrs.d] done.
2025/02/23 11:17:19 | stdout | [fix-attrs.d] applying ownership & permissions fixes...
2025/02/23 11:17:19 | stdout | [s6-init] ensuring user provided files have correct perms...exited 0.
2025/02/23 11:17:19 | stdout | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
```

**Comment by jwetzell** [comment]
That huge list of configured ENV variables is likely the problem. The readme on this repo outlines what ENV variables a user should configure. If you have an other variables specified they should be removed.

**Comment by Aryetis** [comment]
Even when reducing the variables list there is still the same issue.

![Image](https://github.com/user-attachments/assets/2fabfb3e-9e4a-48b5-b271-e7ae9dd639eb)

And sure enough when ssh ing to it, there is no "pg_isready" program in it

**Comment by Aryetis** [comment]
Also all of those env variables are here by default, I added none of them. 

![Image](https://github.com/user-attachments/assets/821564dd-f25e-4603-b355-3a342cd236a3)

Getting the image from here : 
https://hub.docker.com/r/jwetzell/guacamole/

Using a synology ds720+ with DSM 7.2.2-72806 Update 3

**Comment by Aryetis** [comment]
However ... A clean reinstall seems to have fixed the issue... Not sure what happened here.
