### ISSUE TITLE
Security issue - Email is the same as from the forked repo

### ISSUE THREAD

**Issue by mamema** [jwetzell/docker-guacamole#37]
**Describe Your Problem:**
i would like to repport a security issue. But i don't think the email linked in the "Security Reporting" afrea is still valid.

Please provide actual contact information

**Comment by jwetzell** [comment]
I'll have to try and find what section you are talking about with a bad email. But just report what you have here.

**Comment by mamema** [comment]
i mean your own security seciton here: https://github.com/jwetzell/docker-guacamole/security
...and no, vulnerability issues public reporting isn't a good thing. Talk public AFTER fixing it.

**Comment by jwetzell** [comment]
This is a forked repository. I didn't see that doc and have removed it as nothing in there is relevant to this fork. You can send information to me@jwetzell.com if you think the vulnerability lies in this bundling of Apache Guacamole.

**Comment by jwetzell** [comment]
Tomcat has been updated to 9.0.85 and default files cleaned out.

**Comment by mamema** [comment]
thanks
________________________________

**Comment by mamema** [comment]
Hi Joel,

scan from today:
___
Description
The default error page, default index page, example JSPs and/or example servlets are installed on the remote Apache Tomcat server. These files should be removed as they may help an attacker uncover information about the remote Tomcat install or host itself.
Solution
Delete the default index page and remove the example JSP and servlets. Follow the Tomcat or OWASP instructions to replace or modify the default error page.
See Also
http://www.nessus.org/u?4cb3b4dd
https://www.owasp.org/index.php/Securing_tomcat
Output

  *

The server is not configured to return a custom page in the event of a client requesting a non-existent resource.
This may result in a potential disclosure of sensitive information about the server to attackers.


___
so it seems the default files are somwehere still there...
FYI

Best regards

Matt

________________________________

**Comment by jwetzell** [comment]
If you can point to the default files in the container that should be removed I will remove them.
