### ISSUE TITLE
Location of Version Number

### ISSUE THREAD

**Issue by shawnhaywood** [jwetzell/docker-guacamole#41]
**Describe Your Problem:**
Sorry for my ignorance.  Where do I find the version number of my current install.  
I installed the "latest" docker compose several months ago and want to ensure I have the latest version.

**Logs:**

```
```

**Screenshots:**

**Environment:**

* **Guacamole Version**: 
* **Operating System**: Ubuntu

**Comment by jwetzell** [comment]
I'm not sure if there is a way to find the version via the guacamole web ui. You could probably use docker inspect to view the Environment variables which should have the guacamole version that was used. The latest image updates every time I make a change to this repository so if you want to know what version you are running I would suggest specify the version and not using the latest tag.
