### ISSUE TITLE
Branding logo

### ISSUE THREAD

**Issue by netwaze** [jwetzell/docker-guacamole#43]
Hello, since the update 1.5.4 our jar branding file to change the logo etc ... no longer works. 
If we put it in the extensions folder and turn on our docker it is automatically deleted. If we put it in extensions-available it is not taken into account at startup. 
I've added :

    environment:
      EXTENSION: branding

Without success. Do you have a solution? 
Sincerely

**Comment by jwetzell** [comment]
Is this a custom jar that you put in the extensions-available folder and then reference?

**Comment by jwetzell** [comment]
@netwaze I see what change is causing this now. I have pushed modifications to the latest tag that should fix the jar being deleted from the extensions folder. If you could try out the latest tag and see if that fixes this issue, and if that works I will update the 1.5.4 image with this change.
