### ISSUE TITLE
Bump to version 1.5.5

### ISSUE THREAD

**Issue by mariushosting** [jwetzell/docker-guacamole#44]
@jwetzell Please bump guacamole to the new version 1.5.5

**Comment by jwetzell** [comment]
The latest image has been updated to 1.5.5. I will finish testing when I get to computer and if that all checks out tag it as 1.5.5.

**Comment by mariushosting** [comment]
> The latest image has been updated to 1.5.5. I will finish testing when I get to computer and if that all checks out tag it as 1.5.5.

Awesome news !

**Comment by jwetzell** [comment]
1.5.5 has been tagged!
