### ISSUE TITLE
DUO Auth Extension Broken

### ISSUE THREAD

**Issue by KingCaptainX** [jwetzell/docker-guacamole#48]
**Describe Your Problem:**
As of March 2024, DUO has deprecated the use of the Traditional prompt for authenticating their services. I am just now setting up the DUO extension, so will be undoing it until there is an update, but wanted to reach out. The documentation I could find regarding making the update should be able to be found [here](https://duo.com/docs/duoweb). I don't know enough about this process to provide more detail. I don't believe I have any logs for this issue outside of the error messages received in the screenshots below, but let me know if you need anything else from me to move forward. Thank you!

**Logs:**

**Screenshots:**
![image](https://github.com/jwetzell/docker-guacamole/assets/96804798/ff8c547d-2a23-4278-9a1f-44e1c4c253c8)
![image](https://github.com/jwetzell/docker-guacamole/assets/96804798/dd68f24e-ace1-44a3-b1f0-e2a8addaa068)

**Environment:**

* **Guacamole Version**: jwetzell/guacamole:latest
* **Operating System**:  Docker

**Comment by jwetzell** [comment]
Not something I can fix. Looks like Apache has it on the table for 1.6.0 all I can do is wait.
