### ISSUE TITLE
TOTP will not enable.

### ISSUE THREAD

**Issue by Senectus** [jwetzell/docker-guacamole#49]
**Describe The Bug:**

turning on EXTENSIONS auth-totp does not work
The "guacamole-auth-totp-1.5.5.jar" files do not copy across into the "/docker/guacamole/guacamole/extensions" folder and the totp never kicks in.

 
**To Reproduce:**

enable totp, reload contianer not that .jar files dont copy and if you sign in totp never starts
**Expected behavior:**

**Logs:**

```
Remove any sensative information.
```

**Screenshots:**

**Environment:**

* **Guacamole Version**: 
* **Operating System**:

**Comment by jwetzell** [comment]
I'm not sure what that folder is as that isn't the folder in the container that would contain the extension. However, I am unable to reproduce this running `docker run -e EXTENSIONS=auth-totp -p 8080:8080 jwetzell/guacamole:1.5.5` I see that totp is enabled just fine.
