### ISSUE TITLE
Lighter image without postgresql but rather user-mapping.xml

### ISSUE THREAD

**Issue by CypZ** [jwetzell/docker-guacamole#5]
Hi,

Would it be possible to have a lighter version without DB but with the default user-mapping.xml ?

For small installation like mine it would be more than enough as my authentication is done upfront (with authelia) and would save some precious resources in RAM

https://guacamole.apache.org/doc/gug/configuring-guacamole.html

Cheers

**Comment by jwetzell** [comment]
This is meant as a drop-in replacement for the oznu container which includes the database as it is an All-In-One container.
