### ISSUE TITLE
arm64 broken in multi-platform image

### ISSUE THREAD

**Issue by divinehawk** [jwetzell/docker-guacamole#50]
**Describe The Bug:**

Docker image does not work on Raspberry pi (arm64). 

The arm64 image appears to have an x86_64 binary:
bin/execlineb: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped

**To Reproduce:**
docker run \
  -p 8080:8080 \
  -v /opt/guacamole:/config \
  jwetzell/guacamole:latest

**Expected behavior:**
  jwetzell/guacamole:arm64 works
  jwetzell/guacamole:1.5.5 does not
 
**Logs:**

exec /init: exec format error

**Environment:**

* **Operating System**:  Debian 12.6

**Comment by jwetzell** [comment]
Thanks for reporting this, I'll look into what went wrong with those tags. Might take a second for me to get an ARM64 platform up for testing.

**Comment by divinehawk** [comment]
Adding:
`ARG TARGETPLATFORM`
to Dockerfile.base fixes is on my local system. Not sure if github requires it.

**Comment by jwetzell** [comment]
HA, good catch. Not sure how I missed then when I split things into the base/main image. If you could try out the `latest` tag I just pushed with that change to the base and if that works I'll push that back to the 1.5.5 tag.

**Comment by jwetzell** [comment]
@divinehawk I think I've got it built and pushed properly now. If you could check the `jwetzell/guacamole:latest` tag that would be great. I've tested on a 64-bit Pi and now don't get the exec format error.

**Comment by divinehawk** [comment]
It works now. Thanks!

**Comment by jwetzell** [comment]
Perfect! This has been rolled back into the 1.5.5 tag as well as the latest.
