### ISSUE TITLE
Dark Mode?

### ISSUE THREAD

**Issue by pmacpherson68** [jwetzell/docker-guacamole#54]
Would be great if we can add dark mode feature... i see that there are some dark mode plug-ins for other guacamole versions, wondering if they might work with this?

**Comment by jwetzell** [comment]
If you can link to the guacamole plugins I can look at them and potentially add them if they are stable enough. I am not interested in adding any functionality to guacamole myself though.

**Comment by Randymartin1991** [comment]
there is a theme mod already: https://docs.theme-park.dev/themes/guacamole/

**Comment by jwetzell** [comment]
Looks like something super custom and not an actual extension for guacamole so unfortunately not something I would be able to include in this docker image.
