### ISSUE TITLE
Video recording 

### ISSUE THREAD

**Issue by netwaze** [jwetzell/docker-guacamole#55]
Hello, since the last update the record function no longer works. When I look in the logs I get this message: 
ERROR: Creation of recording failed: No such file or directory
but I can write to the recordings directory from the container. 

root@bast:[/opt/Guacamole/guacamole/guacamole]: docker exec -it 111da1f3cca8 /bin/bash
root@111da1f3cca8:/config# ls
guacamole  postgres
root@111da1f3cca8:/config# cd guacamole/
extensions/           guacamole.properties  recordings/
extensions-available/ lib/                  schema/
root@111da1f3cca8:/config# cd guacamole/recordings/
root@111da1f3cca8:/config/guacamole/recordings# ls
root@111da1f3cca8:/config/guacamole/recordings# touch test
root@111da1f3cca8:/config/guacamole/recordings# ls
test
root@111da1f3cca8:/config/guacamole/recordings#

in my guacamole.properties file I have my line : 

`recording-search-path: /config/guacamole/recordings`

and in my machines I have put `${HISTORY_PATH}/${HISTORY_UUID} `as registration path

If you have any idea why this doesn't work, I'd love to hear from you ^^ @jwetzell

**Comment by jwetzell** [comment]
I just tested with the 1.5.5 following the[ documentation here ](https://guacamole.apache.org/doc/gug/recording-playback.html#) to setup recording and it worked just fine. Do you have "automatically create recording path" selected?

**Comment by netwaze** [comment]
`Attaching to Guacamole
Guacamole  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
Guacamole  | [s6-init] ensuring user provided files have correct perms...exited 0.
Guacamole  | [fix-attrs.d] applying ownership & permissions fixes...
Guacamole  | [fix-attrs.d] done.
Guacamole  | [cont-init.d] executing container initialization scripts...
Guacamole  | [cont-init.d] 30-defaults.sh: executing...
Guacamole  | cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
Guacamole  | [cont-init.d] 30-defaults.sh: exited 0.
Guacamole  | [cont-init.d] 40-postgres.sh: executing...
Guacamole  | Database already configured
Guacamole  | [cont-init.d] 40-postgres.sh: exited 0.
Guacamole  | [cont-init.d] 50-extensions.sh: executing...
Guacamole  | Cleaning Extensions from previous Guacamole versions
Guacamole  | Cleaning Extensions
Guacamole  | [cont-init.d] 50-extensions.sh: exited 0.
Guacamole  | [cont-init.d] done.
Guacamole  | [services.d] starting services
Guacamole  | Starting postgres...
Guacamole  | Starting guacamole guacd...
Guacamole  | /tmp:5432 - no response
Guacamole  | Waiting for postgres to come up...
Guacamole  | guacd[270]: INFO:  Guacamole proxy daemon (guacd) version 1.5.5 started
Guacamole  | LOG:  database system was shut down at 2024-11-21 16:19:49 CET
Guacamole  | guacd[270]: INFO:  Listening on host 127.0.0.1, port 4822
Guacamole  | LOG:  MultiXact member wraparound protections are now enabled
Guacamole  | LOG:  database system is ready to accept connections
Guacamole  | [services.d] done.
Guacamole  | LOG:  autovacuum launcher started
Guacamole  | FATAL:  role "root" does not exist
Guacamole  | /tmp:5432 - accepting connections
Guacamole  | Starting guacamole client...
Guacamole  | NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
Guacamole  | 21-Nov-2024 16:20:00.921 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/9.0.93
Guacamole  | 21-Nov-2024 16:20:00.932 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Aug 2 2024 21:24:59 UTC
Guacamole  | 21-Nov-2024 16:20:00.933 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 9.0.93.0
Guacamole  | 21-Nov-2024 16:20:00.935 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
Guacamole  | 21-Nov-2024 16:20:00.936 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            6.1.0-21-amd64
Guacamole  | 21-Nov-2024 16:20:00.936 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
Guacamole  | 21-Nov-2024 16:20:00.936 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /opt/java/openjdk
Guacamole  | 21-Nov-2024 16:20:00.936 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           17.0.12+7
Guacamole  | 21-Nov-2024 16:20:00.937 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Eclipse Adoptium
Guacamole  | 21-Nov-2024 16:20:00.937 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
Guacamole  | 21-Nov-2024 16:20:00.938 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
Guacamole  | 21-Nov-2024 16:20:00.954 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
Guacamole  | 21-Nov-2024 16:20:00.957 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
Guacamole  | 21-Nov-2024 16:20:00.957 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util=ALL-UNNAMED
Guacamole  | 21-Nov-2024 16:20:00.958 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
Guacamole  | 21-Nov-2024 16:20:00.958 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
Guacamole  | 21-Nov-2024 16:20:00.958 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
Guacamole  | 21-Nov-2024 16:20:00.959 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
Guacamole  | 21-Nov-2024 16:20:00.959 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
Guacamole  | 21-Nov-2024 16:20:00.960 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
Guacamole  | 21-Nov-2024 16:20:00.961 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
Guacamole  | 21-Nov-2024 16:20:00.961 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
Guacamole  | 21-Nov-2024 16:20:00.961 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
Guacamole  | 21-Nov-2024 16:20:00.962 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
Guacamole  | 21-Nov-2024 16:20:00.962 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
Guacamole  | 21-Nov-2024 16:20:00.967 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded Apache Tomcat Native library [1.3.1] using APR version [1.7.2].
Guacamole  | 21-Nov-2024 16:20:00.968 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true], UDS [true].
Guacamole  | 21-Nov-2024 16:20:00.971 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
Guacamole  | 21-Nov-2024 16:20:00.974 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 3.0.13 30 Jan 2024]
Guacamole  | 21-Nov-2024 16:20:01.667 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
Guacamole  | 21-Nov-2024 16:20:01.725 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [1207] milliseconds
Guacamole  | 21-Nov-2024 16:20:01.811 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
Guacamole  | 21-Nov-2024 16:20:01.812 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/9.0.93]
Guacamole  | 21-Nov-2024 16:20:01.842 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/ROOT.war]
Guacamole  | 21-Nov-2024 16:20:04.890 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Guacamole  | 16:20:05.548 [main] INFO  o.a.g.environment.LocalEnvironment - GUACAMOLE_HOME is "/config/guacamole".
Guacamole  | 16:20:05.735 [main] INFO  o.a.g.GuacamoleServletContextListener - Read configuration parameters from "/config/guacamole/guacamole.properties".
Guacamole  | 16:20:05.740 [main] INFO  o.a.g.rest.auth.HashTokenSessionMap - Sessions will expire after 60 minutes of inactivity.
Guacamole  | 16:20:06.324 [main] INFO  o.a.g.extension.ExtensionModule - Multiple extensions are installed and will be loaded in order of decreasing priority:
Guacamole  | 16:20:06.325 [main] INFO  o.a.g.extension.ExtensionModule -  - [postgresql] "PostgreSQL Authentication" (/config/guacamole/extensions/guacamole-auth-jdbc-postgresql-1.5.5.jar)
Guacamole  | 16:20:06.325 [main] INFO  o.a.g.extension.ExtensionModule - To change this order, set the "extension-priority" property or rename the extension files. The default priority of extensions is dictated by the sort order of their filenames.
Guacamole  | 16:20:06.411 [main] INFO  o.a.g.extension.ExtensionModule - Extension "Tempname" (tempnamespace) loaded.
Guacamole  | 16:20:08.292 [main] INFO  o.a.g.extension.ExtensionModule - Extension "PostgreSQL Authentication" (postgresql) loaded.
Guacamole  | 16:20:08.526 [main] INFO  o.a.g.t.w.WebSocketTunnelModule - Loading JSR-356 WebSocket support...
Guacamole  | 16:20:09.578 [main] WARN  o.g.jersey.server.wadl.WadlFeature - JAXBContext implementation could not be found. WADL feature is disabled.
Guacamole  | 21-Nov-2024 16:20:10.118 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/ROOT.war] has finished in [8,275] ms
Guacamole  | 21-Nov-2024 16:20:10.136 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
Guacamole  | 21-Nov-2024 16:20:10.173 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [8447] milliseconds
`

**Comment by netwaze** [comment]
I have no log on why it deletes the file guacamole-history-recording-storage-1.5.5.jar

**Comment by jwetzell** [comment]
You should be using the environment variable to specify enabled extensions (see the README for examples). That folder is not to be managed manuallly.

**Comment by netwaze** [comment]
I manage well with the environment variable but my problem is still there.

**Comment by jwetzell** [comment]
What is the value of your `EXTENSIONS` environment variable?

**Comment by netwaze** [comment]
`   environment:
      EXTENSION: history-recording-storage`

**Comment by jwetzell** [comment]
It's plural `EXTENSIONS`
