### ISSUE TITLE
Hangs running

### ISSUE THREAD

**Issue by stanthewizzard** [jwetzell/docker-guacamole#6]
Hello

With this (photon 4 updated)

docker run -p 8433:8080 -v ./config/:/config -e "EXTENSIONS=auth-ldap,auth-duo,auth-totp" jwetzell/guacamole

It hangs indefinitly on this

18-Aug-2022 13:20:08.448 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [9719] milliseconds

Thanks for help

**Comment by jwetzell** [comment]
Closing because of age. If this is still an issue please let me know and I will reopen.
