### ISSUE TITLE
Unable to connect to VNC server.

### ISSUE THREAD

**Issue by lcsfox** [jwetzell/docker-guacamole#9]
Hi,
I'm trying to deploy this image on Pi4 armv7l.
I can get the SSH working without any issues, but I'm having some problems using the VNC connection option.
Log below

`
guacamole    | guacd[281]: INFO:	Creating new client for protocol "vnc"
guacamole    | guacd[281]: INFO:	Connection ID is "$617dcf84-cbc9-4c8e-bd1f-e0ff30292032"
guacamole    | guacd[430]: INFO:	Cursor rendering: local
guacamole    | guacd[430]: INFO:	User "@de8ff7aa-9fd5-40e1-8aa4-7ee89ea30214" joined connection "$617dcf84-cbc9-4c8e-bd1f-e0ff30292032" (1 users now present)
guacamole    | 15:13:43.585 [http-nio-8080-exec-5] INFO  o.a.g.tunnel.TunnelRequestService - User "guacadmin" connected to connection "1".
guacamole    | guacd[430]: ERROR:	Unable to connect to VNC server.
guacamole    | guacd[430]: INFO:	User "@de8ff7aa-9fd5-40e1-8aa4-7ee89ea30214" disconnected (0 users remain)
guacamole    | guacd[430]: INFO:	Last user of connection "$617dcf84-cbc9-4c8e-bd1f-e0ff30292032" disconnected
guacamole    | 15:13:43.638 [http-nio-8080-exec-4] INFO  o.a.g.tunnel.TunnelRequestService - User "guacadmin" disconnected from connection "1". Duration: 53 milliseconds
guacamole    | guacd[281]: INFO:	Connection "$617dcf84-cbc9-4c8e-bd1f-e0ff30292032" removed.
guacamole    | Exception in thread "Thread-11" java.lang.IllegalStateException: Message will not be sent because the WebSocket session has been closed
guacamole    | 	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.writeMessagePart(WsRemoteEndpointImplBase.java:425)
guacamole    | 	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:309)
guacamole    | 	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:250)
guacamole    | 	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendString(WsRemoteEndpointImplBase.java:191)
guacamole    | 	at org.apache.tomcat.websocket.WsRemoteEndpointBasic.sendText(WsRemoteEndpointBasic.java:37)
guacamole    | 	at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint.sendInstruction(GuacamoleWebSocketTunnelEndpoint.java:152)
guacamole    | 	at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint.access$200(GuacamoleWebSocketTunnelEndpoint.java:53)
guacamole    | 	at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint$2.run(GuacamoleWebSocketTunnelEndpoint.java:253)
`

Same image on x64 cpu works fine

**Comment by jwetzell** [comment]
Is this still an issue?

**Comment by jwetzell** [comment]
closing due to no response, if this is still an issue please reopen.
